name: build_main

on:
  push:
    branches:
      - main

jobs:
  build-project:
    env:
      GPR_USERNAME: ${{ github.actor }}
      GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Update Version
        run: npm run bump-release # Updates the semantic version depending on the last commits e.g. feature / bugfix

      - name: Set Snapshot Version
        run: ./gradlew setSnapshotVersion # Do not chain this command because it writes into a file which needs to be re-read inside the next gradle command

      - name: Assemble release .apk
        run: ./gradlew assembleRelease

      - name: Archive .apk file
        uses: actions/upload-artifact@v3
        with:
          name: kuksa_companion_app.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Archive changelog
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
