name: build_main

on:
  push:
    branches:
      - main

jobs:
  build-project:
    uses: ./.github/workflows/reusable_build_validation.yaml

  deploy-artifacts:
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Archive .apk file
        uses: actions/upload-artifact@v3
        with:
          name: kuksa_companion_app.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk

      - name: Archive changelog
        uses: actions/upload-artifact@v3
        with:
          name: CHANGELOG.md
          path: CHANGELOG.md
