name: Validate pull request

on:
  pull_request

env:
  GPR_USERNAME: ${{ github.actor }}
  GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  validate-project:
    uses: ./.github/workflows/reusable-build-validation.yaml

  build-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Project
        uses: ./.github/actions/setup-project

      - name: Update Version
        run: npm run bump-release # Updates the semantic version depending on the last commits e.g. feature / bugfix

      - name: Set Snapshot Version
        run: ./gradlew setSnapshotVersion # Do not chain this command because it writes into a file which needs to be re-read inside the next gradle command

      - name: Build 'assembleDebug' with Gradle Wrapper
        run: ./gradlew assembleDebug

      - name: Archive .apk file
        uses: actions/upload-artifact@v3
        with:
          name: kuksa_companion_app.snapshot.apk
          path: app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
          retention-days: 14
