name: create-release

concurrency: production

on:
  push:
    tags:
      - 'release/v*'

permissions:
  contents: write

jobs:
  deployment:
    env:
      GPR_USERNAME: ${{ github.actor }}
      GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set Release Version
        run: ./gradlew setReleaseVersion # Do not chain this command because it writes into a file which needs to be re-read inside the next gradle command

      - name: Create .apk file
        run: ./gradlew assembleRelease

      - name: Rename release artefact
        run: mv app/build/outputs/apk/release/app-release-unsigned.apk kuksa_companion_app.apk

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          body_path: CHANGELOG.md
          files: |
            CHANGELOG.md
            kuksa_companion_app.apk
            
